display_name: AKV VPN
publisher_display_name: AKV VPN
identity_name: com.akv.vpn
msix_version: 4.1.2.0
logo_path: windows\runner\resources\app_icon.ico
capabilities: internetClient, internetClientServer, privateNetworkClientServer
languages: ar, en-us, es-es, fa-ir, fr-fr, id-id, pt-br, ru-ru, tr-tr, zh-cn, zh-tw
protocol_activation: akvvpn
execution_alias: akvvpn
certificate_path: windows\sign.pfx
certificate_password:
publisher: CN=AKV VPN
install_certificate: "false"
enable_at_startup: "true"
startup_task:
  parameters: --autostart

# For testing with a self-signed certificate
# publisher: CN=AKV-VPN-Test
# certificate_password: "1234"
# install_certificate: "true"
