app_id: 5F97C0B8-68F5-4FE3-A067-219E66A0BBA4
publisher: AKV VPN
publisher_url: https://github.com/Lujker/akv-vpn-app
display_name: AKV VPN
create_desktop_icon: true
install_dir_name: "{autopf64}\\AKV VPN"
setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - ar
  - en
  - es
  - fr
  - pt
  - ru
  - tr
script_template: inno_setup.sas
